kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-configmap
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    protected-mode no
    requirepass 123456
    pidfile /data/redis-6379.pid