// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: business/message.ext.proto

package businesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageExtService_SendFriendMessage_FullMethodName = "/business.MessageExtService/SendFriendMessage"
	MessageExtService_SendGroupMessage_FullMethodName  = "/business.MessageExtService/SendGroupMessage"
	MessageExtService_SendRoomMessage_FullMethodName   = "/business.MessageExtService/SendRoomMessage"
)

// MessageExtServiceClient is the client API for MessageExtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageExtServiceClient interface {
	// 发送好友消息
	SendFriendMessage(ctx context.Context, in *SendFriendMessageRequest, opts ...grpc.CallOption) (*SendFriendMessageReply, error)
	// 发送群组信息
	SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageReply, error)
	// 发送房间信息
	SendRoomMessage(ctx context.Context, in *SendRoomMessageRequest, opts ...grpc.CallOption) (*SendRoomMessageReply, error)
}

type messageExtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageExtServiceClient(cc grpc.ClientConnInterface) MessageExtServiceClient {
	return &messageExtServiceClient{cc}
}

func (c *messageExtServiceClient) SendFriendMessage(ctx context.Context, in *SendFriendMessageRequest, opts ...grpc.CallOption) (*SendFriendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendMessageReply)
	err := c.cc.Invoke(ctx, MessageExtService_SendFriendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageExtServiceClient) SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupMessageReply)
	err := c.cc.Invoke(ctx, MessageExtService_SendGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageExtServiceClient) SendRoomMessage(ctx context.Context, in *SendRoomMessageRequest, opts ...grpc.CallOption) (*SendRoomMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRoomMessageReply)
	err := c.cc.Invoke(ctx, MessageExtService_SendRoomMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageExtServiceServer is the server API for MessageExtService service.
// All implementations must embed UnimplementedMessageExtServiceServer
// for forward compatibility.
type MessageExtServiceServer interface {
	// 发送好友消息
	SendFriendMessage(context.Context, *SendFriendMessageRequest) (*SendFriendMessageReply, error)
	// 发送群组信息
	SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageReply, error)
	// 发送房间信息
	SendRoomMessage(context.Context, *SendRoomMessageRequest) (*SendRoomMessageReply, error)
	mustEmbedUnimplementedMessageExtServiceServer()
}

// UnimplementedMessageExtServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageExtServiceServer struct{}

func (UnimplementedMessageExtServiceServer) SendFriendMessage(context.Context, *SendFriendMessageRequest) (*SendFriendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFriendMessage not implemented")
}
func (UnimplementedMessageExtServiceServer) SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGroupMessage not implemented")
}
func (UnimplementedMessageExtServiceServer) SendRoomMessage(context.Context, *SendRoomMessageRequest) (*SendRoomMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRoomMessage not implemented")
}
func (UnimplementedMessageExtServiceServer) mustEmbedUnimplementedMessageExtServiceServer() {}
func (UnimplementedMessageExtServiceServer) testEmbeddedByValue()                           {}

// UnsafeMessageExtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageExtServiceServer will
// result in compilation errors.
type UnsafeMessageExtServiceServer interface {
	mustEmbedUnimplementedMessageExtServiceServer()
}

func RegisterMessageExtServiceServer(s grpc.ServiceRegistrar, srv MessageExtServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageExtServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageExtService_ServiceDesc, srv)
}

func _MessageExtService_SendFriendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageExtServiceServer).SendFriendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageExtService_SendFriendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageExtServiceServer).SendFriendMessage(ctx, req.(*SendFriendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageExtService_SendGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageExtServiceServer).SendGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageExtService_SendGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageExtServiceServer).SendGroupMessage(ctx, req.(*SendGroupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageExtService_SendRoomMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRoomMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageExtServiceServer).SendRoomMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageExtService_SendRoomMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageExtServiceServer).SendRoomMessage(ctx, req.(*SendRoomMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageExtService_ServiceDesc is the grpc.ServiceDesc for MessageExtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageExtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "business.MessageExtService",
	HandlerType: (*MessageExtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendMessage",
			Handler:    _MessageExtService_SendFriendMessage_Handler,
		},
		{
			MethodName: "SendGroupMessage",
			Handler:    _MessageExtService_SendGroupMessage_Handler,
		},
		{
			MethodName: "SendRoomMessage",
			Handler:    _MessageExtService_SendRoomMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/message.ext.proto",
}
