// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	MessageItem
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息投递
type Message struct {
	Type     int32          `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Messages []*MessageItem `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return messageFileDescriptor, []int{0} }

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 单条消息投递
type MessageItem struct {
	MessageId      int64  `protobuf:"varint,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	SenderType     int32  `protobuf:"varint,2,opt,name=sender_type,json=senderType" json:"sender_type,omitempty"`
	SenderId       int64  `protobuf:"varint,3,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	SenderDeviceId int64  `protobuf:"varint,4,opt,name=sender_device_id,json=senderDeviceId" json:"sender_device_id,omitempty"`
	ReceiverType   int32  `protobuf:"varint,5,opt,name=receiver_type,json=receiverType" json:"receiver_type,omitempty"`
	ReceiverId     int64  `protobuf:"varint,6,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Type           int32  `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	Content        string `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
	SyncSequence   int64  `protobuf:"varint,9,opt,name=sync_sequence,json=syncSequence" json:"sync_sequence,omitempty"`
	SendTime       int64  `protobuf:"varint,10,opt,name=send_time,json=sendTime" json:"send_time,omitempty"`
}

func (m *MessageItem) Reset()                    { *m = MessageItem{} }
func (m *MessageItem) String() string            { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()               {}
func (*MessageItem) Descriptor() ([]byte, []int) { return messageFileDescriptor, []int{1} }

func (m *MessageItem) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageItem) GetSenderType() int32 {
	if m != nil {
		return m.SenderType
	}
	return 0
}

func (m *MessageItem) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MessageItem) GetSenderDeviceId() int64 {
	if m != nil {
		return m.SenderDeviceId
	}
	return 0
}

func (m *MessageItem) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *MessageItem) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MessageItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageItem) GetSyncSequence() int64 {
	if m != nil {
		return m.SyncSequence
	}
	return 0
}

func (m *MessageItem) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageItem)(nil), "pb.MessageItem")
}

func init() { proto.RegisterFile("message.proto", messageFileDescriptor) }

var messageFileDescriptor = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x53, 0x68, 0x0b, 0x0c, 0xad, 0x9a, 0x3d, 0x6d, 0x62, 0x4c, 0x49, 0xbd, 0x90, 0x98,
	0x70, 0xd0, 0x57, 0xf0, 0xb2, 0x26, 0x5e, 0xb0, 0x77, 0x22, 0xbb, 0x13, 0xb3, 0x07, 0x16, 0x64,
	0xd7, 0x26, 0x7d, 0x45, 0x9f, 0xca, 0x30, 0xec, 0x62, 0x6f, 0xf0, 0xcd, 0x3f, 0xf3, 0x65, 0x66,
	0x61, 0xdf, 0xa1, 0xb5, 0x9f, 0x5f, 0x58, 0x0d, 0x63, 0xef, 0x7a, 0x16, 0x0d, 0xed, 0xf1, 0x0d,
	0x92, 0xf7, 0x19, 0x32, 0x06, 0x6b, 0x77, 0x19, 0x90, 0xaf, 0x8a, 0x55, 0xb9, 0xa9, 0xe9, 0x9b,
	0x3d, 0x41, 0xea, 0x7b, 0x2c, 0x8f, 0x8a, 0xb8, 0xcc, 0x9f, 0x6f, 0xab, 0xa1, 0xad, 0x7c, 0x8b,
	0x70, 0xd8, 0xd5, 0x4b, 0xe0, 0xf8, 0x1b, 0x41, 0x7e, 0x55, 0x61, 0x0f, 0x00, 0xbe, 0xd6, 0x68,
	0x45, 0x63, 0xe3, 0x3a, 0xf3, 0x44, 0x28, 0x76, 0x80, 0xdc, 0xa2, 0x51, 0x38, 0x36, 0xa4, 0x8d,
	0x48, 0x0b, 0x33, 0x3a, 0x4d, 0xf2, 0x7b, 0xc8, 0x7c, 0x40, 0x2b, 0x1e, 0x53, 0x7b, 0x3a, 0x03,
	0xa1, 0x58, 0x09, 0x77, 0xbe, 0xa8, 0xf0, 0xac, 0x25, 0x29, 0xd6, 0x94, 0xb9, 0x99, 0xf9, 0x2b,
	0x61, 0xa1, 0xd8, 0x23, 0xec, 0x47, 0x94, 0xa8, 0xcf, 0xc1, 0xb4, 0x21, 0xd3, 0x2e, 0x40, 0x72,
	0x1d, 0x20, 0x5f, 0x42, 0x5a, 0xf1, 0x2d, 0x4d, 0x82, 0x80, 0x84, 0x5a, 0xae, 0x93, 0x5c, 0x5d,
	0x87, 0x43, 0x22, 0x7b, 0xe3, 0xd0, 0x38, 0x9e, 0x16, 0xab, 0x32, 0xab, 0xc3, 0xef, 0xe4, 0xb4,
	0x17, 0x23, 0x1b, 0x8b, 0xdf, 0x3f, 0x68, 0x24, 0xf2, 0x8c, 0x06, 0xee, 0x26, 0xf8, 0xe1, 0x59,
	0xd8, 0xaf, 0x71, 0xba, 0x43, 0x0e, 0xff, 0xfb, 0x9d, 0x74, 0x87, 0xed, 0x96, 0xde, 0xe8, 0xe5,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x16, 0x5a, 0x90, 0xe3, 0xb4, 0x01, 0x00, 0x00,
}
