# deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-deployment
  labels:
    app: {{ .Values.server.business.name }}
spec:
  replicas: {{ .Values.server.business.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.business.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.business.name }}
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', "until nslookup mysql-stateful-set-0.mysql.default.svc.cluster.local; do echo waiting for mysql; sleep 1; done" ]
        - name: init-redis
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', "until nslookup redis-stateful-set-0.redis.default.svc.cluster.local; do echo waiting for redis; sleep 1; done" ]
      containers:
        - name: {{ .Values.server.business.name }}
          image: {{ .Values.server.business.image }}
          imagePullPolicy: IfNotPresent     # 在kind中需要指定，不然会强制到远程拉取镜像，导致部署失败
          ports:
            - containerPort: 8000
              hostPort: 8020
          volumeMounts: # 映射文件为宿主机文件
            - mountPath: /data/log/business
              name: log
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV
              value: {{ $.Values.env }}
            - name: SERVER
              value: {{ $.Values.server.business.name }}
      volumes:
        - name: log
          hostPath:
            path: /data/log/business
---
# service 配置
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.business.name }}
  labels:
    app: {{ .Values.server.business.name }}  # 只有设置label,才能被服务发现找到
spec:
  selector:
    app: {{ .Values.server.business.name }}
  ports:
    - name: rpc
      protocol: TCP
      port: 8000
      targetPort: 8000
