# deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-deployment
  labels:
    app: {{ .Values.server.logic.name }}
spec:
  replicas: {{ .Values.server.logic.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.logic.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.logic.name }}
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', "until nslookup mysql-stateful-set-0.mysql.default.svc.cluster.local; do echo waiting for mysql; sleep 1; done" ]
        - name: init-redis
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', "until nslookup redis-stateful-set-0.redis.default.svc.cluster.local; do echo waiting for redis; sleep 1; done" ]
      containers:
        - name: {{ .Values.server.logic.name }}
          image: {{ .Values.server.logic.image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/log/logic
              name: log
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV
              value: {{ $.Values.env }}
            - name: SERVER
              value: {{ $.Values.server.logic.name }}
      volumes:
        - name: log
          hostPath:
            path: /data/log/logic
---
# service 配置
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.logic.name }}
  labels:
    app: {{ .Values.server.logic.name }}
spec:
  selector:
    app: {{ .Values.server.logic.name }}
  ports:
    - name: rpc
      protocol: TCP
      port: 8000
      targetPort: 8000
