# 本地开发环境
name: gim
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0.43
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      ENV: compose
    volumes:
      - /etc/localtime:/etc/localtime
      - /Users/alber/data/gim_compose/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ../../sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    restart: always
    image: redis:7.4.2
    volumes:
      - /etc/localtime:/etc/localtime
      - ./redis.conf:/etc/redis.conf
      - /Users/alber/data/gim_compose/redis:/data
    command: redis-server /etc/redis.conf
    ports:
      - "6379:6379"
    environment:
      ENV: compose
  connect:
    container_name: connect
    restart: always
    image: connect:20260504.193325
    volumes:
      - /etc/localtime:/etc/localtime
      - /Users/alber/data/gim_compose/log/connect:/data/log/connect
    ports:
      - "8002:8002"
      - "8003:8003"
    environment:
      ENV: compose
      SERVER: connect
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
  logic:
    container_name: logic
    restart: always
    image: logic:20260504.193332
    volumes:
      - /etc/localtime:/etc/localtime
      - /Users/alber/data/gim_compose/log/logic:/data/log/logic
    environment:
      ENV: compose
      SERVER: logic
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
  business:
    container_name: business
    restart: always
    image: business:20260504.193337
    volumes:
      - /etc/localtime:/etc/localtime
      - /Users/alber/data/gim_compose/log//business:/data/log/business
      - /Users/alber/data/gim_compose/file:/data/file
    ports:
      - "8081:8081"
    environment:
      ENV: compose
      SERVER: business
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
  proxy:
    container_name: proxy
    restart: always
    image: proxy:20260504.193341
    volumes:
      - /etc/localtime:/etc/localtime
      - /Users/alber/data/gim_compose/log//proxy:/data/log/proxy
    ports:
      - "8080:8080"
    environment:
      ENV: compose
      SERVER: proxy
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
