// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: logic/friend.ext.proto

package logicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendFriendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 接收者ID，用户ID/群组ID
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`              // 推动内容
}

func (x *SendFriendMessageRequest) Reset() {
	*x = SendFriendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendMessageRequest) ProtoMessage() {}

func (x *SendFriendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendFriendMessageRequest) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendMessageRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendFriendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendFriendMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId uint64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 消息序列号
}

func (x *SendFriendMessageReply) Reset() {
	*x = SendFriendMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendMessageReply) ProtoMessage() {}

func (x *SendFriendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendMessageReply.ProtoReflect.Descriptor instead.
func (*SendFriendMessageReply) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendMessageReply) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type FriendAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId    uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 用户id
	Remarks     string `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`                    // 备注
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`            // 描述
}

func (x *FriendAddRequest) Reset() {
	*x = FriendAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddRequest) ProtoMessage() {}

func (x *FriendAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddRequest.ProtoReflect.Descriptor instead.
func (*FriendAddRequest) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{2}
}

func (x *FriendAddRequest) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendAddRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *FriendAddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FriendAgreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Remarks string `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`              // 备注
}

func (x *FriendAgreeRequest) Reset() {
	*x = FriendAgreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendAgreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAgreeRequest) ProtoMessage() {}

func (x *FriendAgreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAgreeRequest.ProtoReflect.Descriptor instead.
func (*FriendAgreeRequest) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{3}
}

func (x *FriendAgreeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendAgreeRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type FriendSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友id
	Remarks  string `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`                    // 备注
	Extra    string `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                        // 附加字段
}

func (x *FriendSetRequest) Reset() {
	*x = FriendSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendSetRequest) ProtoMessage() {}

func (x *FriendSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendSetRequest.ProtoReflect.Descriptor instead.
func (*FriendSetRequest) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{4}
}

func (x *FriendSetRequest) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendSetRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *FriendSetRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type FriendSetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友id
	Remarks  string `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`                    // 备注
	Extra    string `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                        // 附加字段
}

func (x *FriendSetReply) Reset() {
	*x = FriendSetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendSetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendSetReply) ProtoMessage() {}

func (x *FriendSetReply) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendSetReply.ProtoReflect.Descriptor instead.
func (*FriendSetReply) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{5}
}

func (x *FriendSetReply) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendSetReply) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *FriendSetReply) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type Friend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户id
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 电话号码
	Nickname    string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                          // 昵称
	Sex         int32  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`                                   // 性别
	AvatarUrl   string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`       // 头像地址
	UserExtra   string `protobuf:"bytes,6,opt,name=user_extra,json=userExtra,proto3" json:"user_extra,omitempty"`       // 用户附加字段
	Remarks     string `protobuf:"bytes,7,opt,name=remarks,proto3" json:"remarks,omitempty"`                            // 备注
	Extra       string `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                                // 附加字段
}

func (x *Friend) Reset() {
	*x = Friend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{6}
}

func (x *Friend) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Friend) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Friend) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Friend) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Friend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Friend) GetUserExtra() string {
	if x != nil {
		return x.UserExtra
	}
	return ""
}

func (x *Friend) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *Friend) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type GetFriendsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*Friend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
}

func (x *GetFriendsReply) Reset() {
	*x = GetFriendsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_friend_ext_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsReply) ProtoMessage() {}

func (x *GetFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_logic_friend_ext_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsReply.ProtoReflect.Descriptor instead.
func (*GetFriendsReply) Descriptor() ([]byte, []int) {
	return file_logic_friend_ext_proto_rawDescGZIP(), []int{7}
}

func (x *GetFriendsReply) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_logic_friend_ext_proto protoreflect.FileDescriptor

var file_logic_friend_ext_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x65,
	0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x18,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x16, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x10, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x47, 0x0a, 0x12, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x67, 0x72, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x5f, 0x0a, 0x10, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x5d, 0x0a, 0x0e, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0xe0, 0x01, 0x0a, 0x06, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x3a, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x27, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x32, 0xca, 0x02, 0x0a, 0x10, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d,
	0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x17, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x41, 0x67, 0x72, 0x65, 0x65, 0x12, 0x19,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x67, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x35, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x6d, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logic_friend_ext_proto_rawDescOnce sync.Once
	file_logic_friend_ext_proto_rawDescData = file_logic_friend_ext_proto_rawDesc
)

func file_logic_friend_ext_proto_rawDescGZIP() []byte {
	file_logic_friend_ext_proto_rawDescOnce.Do(func() {
		file_logic_friend_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_logic_friend_ext_proto_rawDescData)
	})
	return file_logic_friend_ext_proto_rawDescData
}

var file_logic_friend_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_logic_friend_ext_proto_goTypes = []interface{}{
	(*SendFriendMessageRequest)(nil), // 0: logic.SendFriendMessageRequest
	(*SendFriendMessageReply)(nil),   // 1: logic.SendFriendMessageReply
	(*FriendAddRequest)(nil),         // 2: logic.FriendAddRequest
	(*FriendAgreeRequest)(nil),       // 3: logic.FriendAgreeRequest
	(*FriendSetRequest)(nil),         // 4: logic.FriendSetRequest
	(*FriendSetReply)(nil),           // 5: logic.FriendSetReply
	(*Friend)(nil),                   // 6: logic.Friend
	(*GetFriendsReply)(nil),          // 7: logic.GetFriendsReply
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_logic_friend_ext_proto_depIdxs = []int32{
	6, // 0: logic.GetFriendsReply.friends:type_name -> logic.Friend
	0, // 1: logic.FriendExtService.SendMessage:input_type -> logic.SendFriendMessageRequest
	2, // 2: logic.FriendExtService.Add:input_type -> logic.FriendAddRequest
	3, // 3: logic.FriendExtService.Agree:input_type -> logic.FriendAgreeRequest
	4, // 4: logic.FriendExtService.Set:input_type -> logic.FriendSetRequest
	8, // 5: logic.FriendExtService.GetFriends:input_type -> google.protobuf.Empty
	1, // 6: logic.FriendExtService.SendMessage:output_type -> logic.SendFriendMessageReply
	8, // 7: logic.FriendExtService.Add:output_type -> google.protobuf.Empty
	8, // 8: logic.FriendExtService.Agree:output_type -> google.protobuf.Empty
	5, // 9: logic.FriendExtService.Set:output_type -> logic.FriendSetReply
	7, // 10: logic.FriendExtService.GetFriends:output_type -> logic.GetFriendsReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logic_friend_ext_proto_init() }
func file_logic_friend_ext_proto_init() {
	if File_logic_friend_ext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logic_friend_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendAgreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendSetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_friend_ext_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logic_friend_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logic_friend_ext_proto_goTypes,
		DependencyIndexes: file_logic_friend_ext_proto_depIdxs,
		MessageInfos:      file_logic_friend_ext_proto_msgTypes,
	}.Build()
	File_logic_friend_ext_proto = out.File
	file_logic_friend_ext_proto_rawDesc = nil
	file_logic_friend_ext_proto_goTypes = nil
	file_logic_friend_ext_proto_depIdxs = nil
}
