syntax = "proto3";
package logic;
option go_package = "gim/pkg/protocol/pb/logicpb";

import "google/protobuf/empty.proto";

import "connect/connect.ext.proto";

service MessageIntService {
  // 推送
  rpc PushToUsers (PushToUsersRequest) returns (PushToUsersReply);
  // 全服推送
  rpc PushToAll(PushToAllRequest)returns(google.protobuf.Empty);
}


message PushToUsersRequest{
  uint64 from_user_id = 1; // 消息发送用户ID
  repeated uint64 user_ids = 2; // 用户ID列表
  connect.MessageCommand command = 3; // 推送码
  bytes content = 4; // 推送内容
  bool is_persist = 5; // 是否持久化
}
message PushToUsersReply{
  uint64 message_id = 1; // 消息ID
  uint64 from_user_seq = 2; // 用户序列号
}

message PushToAllRequest{
  connect.MessageCommand command = 1; // 推送码
  bytes content = 2; // 推送内容
}