// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conn.int.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliverMessageReq struct {
	DeviceId             int64        `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Fd                   int64        `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	MessageSend          *MessageSend `protobuf:"bytes,3,opt,name=message_send,json=messageSend,proto3" json:"message_send,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeliverMessageReq) Reset()         { *m = DeliverMessageReq{} }
func (m *DeliverMessageReq) String() string { return proto.CompactTextString(m) }
func (*DeliverMessageReq) ProtoMessage()    {}
func (*DeliverMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f4fa8148a89d3, []int{0}
}

func (m *DeliverMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverMessageReq.Unmarshal(m, b)
}
func (m *DeliverMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverMessageReq.Marshal(b, m, deterministic)
}
func (m *DeliverMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverMessageReq.Merge(m, src)
}
func (m *DeliverMessageReq) XXX_Size() int {
	return xxx_messageInfo_DeliverMessageReq.Size(m)
}
func (m *DeliverMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverMessageReq proto.InternalMessageInfo

func (m *DeliverMessageReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *DeliverMessageReq) GetFd() int64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *DeliverMessageReq) GetMessageSend() *MessageSend {
	if m != nil {
		return m.MessageSend
	}
	return nil
}

type DeliverMessageResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverMessageResp) Reset()         { *m = DeliverMessageResp{} }
func (m *DeliverMessageResp) String() string { return proto.CompactTextString(m) }
func (*DeliverMessageResp) ProtoMessage()    {}
func (*DeliverMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f4fa8148a89d3, []int{1}
}

func (m *DeliverMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverMessageResp.Unmarshal(m, b)
}
func (m *DeliverMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverMessageResp.Marshal(b, m, deterministic)
}
func (m *DeliverMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverMessageResp.Merge(m, src)
}
func (m *DeliverMessageResp) XXX_Size() int {
	return xxx_messageInfo_DeliverMessageResp.Size(m)
}
func (m *DeliverMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverMessageResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeliverMessageReq)(nil), "pb.DeliverMessageReq")
	proto.RegisterType((*DeliverMessageResp)(nil), "pb.DeliverMessageResp")
}

func init() { proto.RegisterFile("conn.int.proto", fileDescriptor_b22f4fa8148a89d3) }

var fileDescriptor_b22f4fa8148a89d3 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xcb,
	0xd3, 0xcb, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x82,
	0x88, 0xa5, 0x56, 0x40, 0xc5, 0x94, 0x4a, 0xb8, 0x04, 0x5d, 0x52, 0x73, 0x32, 0xcb, 0x52, 0x8b,
	0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x83, 0x52, 0x0b, 0x85, 0xa4, 0xb9, 0x38, 0x53, 0x52,
	0xcb, 0x32, 0x93, 0x53, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x38, 0x20,
	0x02, 0x9e, 0x29, 0x42, 0x7c, 0x5c, 0x4c, 0x69, 0x29, 0x12, 0x4c, 0x60, 0x51, 0xa6, 0xb4, 0x14,
	0x21, 0x23, 0x2e, 0x9e, 0x5c, 0x88, 0xd6, 0xf8, 0xe2, 0xd4, 0xbc, 0x14, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x7e, 0xbd, 0x82, 0x24, 0x3d, 0xa8, 0x91, 0xc1, 0xa9, 0x79, 0x29, 0x41, 0xdc,
	0xb9, 0x08, 0x8e, 0x92, 0x08, 0x97, 0x10, 0xba, 0xad, 0xc5, 0x05, 0x46, 0x5e, 0x5c, 0xec, 0xce,
	0xf9, 0x79, 0x79, 0x9e, 0x79, 0x25, 0x42, 0xf6, 0x5c, 0x7c, 0xa8, 0x0a, 0x84, 0x44, 0x41, 0x06,
	0x62, 0x38, 0x55, 0x4a, 0x0c, 0x9b, 0x70, 0x71, 0x41, 0x12, 0x1b, 0xd8, 0x7b, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x35, 0xcd, 0xe9, 0xb8, 0x04, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnIntClient is the client API for ConnInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnIntClient interface {
	//  消息投递
	DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error)
}

type connIntClient struct {
	cc *grpc.ClientConn
}

func NewConnIntClient(cc *grpc.ClientConn) ConnIntClient {
	return &connIntClient{cc}
}

func (c *connIntClient) DeliverMessage(ctx context.Context, in *DeliverMessageReq, opts ...grpc.CallOption) (*DeliverMessageResp, error) {
	out := new(DeliverMessageResp)
	err := c.cc.Invoke(ctx, "/pb.ConnInt/DeliverMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnIntServer is the server API for ConnInt service.
type ConnIntServer interface {
	//  消息投递
	DeliverMessage(context.Context, *DeliverMessageReq) (*DeliverMessageResp, error)
}

// UnimplementedConnIntServer can be embedded to have forward compatible implementations.
type UnimplementedConnIntServer struct {
}

func (*UnimplementedConnIntServer) DeliverMessage(ctx context.Context, req *DeliverMessageReq) (*DeliverMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverMessage not implemented")
}

func RegisterConnIntServer(s *grpc.Server, srv ConnIntServer) {
	s.RegisterService(&_ConnInt_serviceDesc, srv)
}

func _ConnInt_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnIntServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConnInt/DeliverMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnIntServer).DeliverMessage(ctx, req.(*DeliverMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnInt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConnInt",
	HandlerType: (*ConnIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _ConnInt_DeliverMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conn.int.proto",
}
