// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.int.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *AuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{1}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

type GetUsersReq struct {
	UserIds              []int64  `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersReq) Reset()         { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()    {}
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{2}
}

func (m *GetUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReq.Unmarshal(m, b)
}
func (m *GetUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReq.Marshal(b, m, deterministic)
}
func (m *GetUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReq.Merge(m, src)
}
func (m *GetUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetUsersReq.Size(m)
}
func (m *GetUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReq proto.InternalMessageInfo

func (m *GetUsersReq) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetUsersResp struct {
	Users                map[int64]*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUsersResp) Reset()         { *m = GetUsersResp{} }
func (m *GetUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp) ProtoMessage()    {}
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a691eb292bdaab8c, []int{3}
}

func (m *GetUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp.Unmarshal(m, b)
}
func (m *GetUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp.Marshal(b, m, deterministic)
}
func (m *GetUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp.Merge(m, src)
}
func (m *GetUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp.Size(m)
}
func (m *GetUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp proto.InternalMessageInfo

func (m *GetUsersResp) GetUsers() map[int64]*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "pb.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "pb.AuthResp")
	proto.RegisterType((*GetUsersReq)(nil), "pb.GetUsersReq")
	proto.RegisterType((*GetUsersResp)(nil), "pb.GetUsersResp")
	proto.RegisterMapType((map[int64]*User)(nil), "pb.GetUsersResp.UsersEntry")
}

func init() { proto.RegisterFile("user.int.proto", fileDescriptor_a691eb292bdaab8c) }

var fileDescriptor_a691eb292bdaab8c = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xdf, 0x4b, 0x83, 0x50,
	0x14, 0xe6, 0x6a, 0x4e, 0x77, 0x1c, 0xdb, 0x38, 0x04, 0x99, 0x83, 0x30, 0x9f, 0x24, 0x48, 0xc8,
	0x5e, 0xa2, 0xb7, 0x82, 0x08, 0x5f, 0x2f, 0xec, 0x39, 0x32, 0x2f, 0x24, 0x0b, 0xbd, 0xf3, 0x5e,
	0x47, 0xfb, 0x03, 0xa2, 0x7f, 0x3b, 0x8e, 0xd7, 0x70, 0xdb, 0xdb, 0xf9, 0x7e, 0x78, 0xbe, 0xf3,
	0x79, 0x61, 0xde, 0x29, 0xd1, 0xa6, 0x55, 0xad, 0x53, 0xd9, 0x36, 0xba, 0x41, 0x4b, 0x16, 0xa1,
	0xe1, 0xc4, 0xf7, 0xc0, 0xc5, 0x6b, 0x70, 0x9f, 0x3a, 0xfd, 0xc9, 0xc5, 0x16, 0x2f, 0xc0, 0x25,
	0xf1, 0xad, 0x2a, 0x03, 0x16, 0xb1, 0xc4, 0xe6, 0x13, 0x82, 0x79, 0x89, 0x2b, 0x98, 0x96, 0x62,
	0x57, 0x7d, 0x08, 0x92, 0xac, 0x5e, 0xf2, 0x0c, 0x91, 0x97, 0x78, 0x0e, 0x8e, 0x6e, 0x36, 0xa2,
	0x0e, 0xec, 0x88, 0x25, 0x53, 0x6e, 0x40, 0x0c, 0xe0, 0x99, 0xb5, 0x4a, 0xc6, 0x09, 0xf8, 0xaf,
	0x42, 0xaf, 0x95, 0x68, 0x15, 0xc5, 0x5c, 0x82, 0x37, 0xc4, 0xa8, 0x80, 0x45, 0x76, 0x62, 0x73,
	0xd7, 0xe4, 0xa8, 0xf8, 0x87, 0xc1, 0x6c, 0xb4, 0x2a, 0x89, 0x77, 0xe0, 0x90, 0x66, 0x8c, 0x7e,
	0xb6, 0x4a, 0x65, 0x91, 0x1e, 0x1a, 0xd2, 0x7e, 0x7a, 0xa9, 0x75, 0xbb, 0xe7, 0xc6, 0x19, 0x3e,
	0x03, 0x8c, 0x24, 0x2e, 0xc1, 0xde, 0x88, 0xfd, 0xd0, 0x87, 0x46, 0xbc, 0x02, 0x67, 0xf7, 0xfe,
	0xd5, 0x89, 0xbe, 0x88, 0x9f, 0x79, 0xb4, 0x92, 0x3e, 0xe0, 0x86, 0x7e, 0xb4, 0x1e, 0x58, 0xf6,
	0xcb, 0xc0, 0x25, 0x2e, 0xaf, 0x35, 0x5e, 0xc3, 0x19, 0x35, 0x41, 0x9f, 0x8c, 0xc3, 0xaf, 0x0a,
	0x67, 0x23, 0x50, 0x12, 0x6f, 0xc0, 0x1d, 0x8e, 0xc2, 0xf9, 0xc1, 0x85, 0x64, 0x5c, 0x1c, 0x61,
	0x25, 0xf1, 0x16, 0xbc, 0xff, 0x02, 0xb8, 0x38, 0xae, 0xb3, 0x0d, 0x97, 0xa7, 0xfd, 0x8a, 0x49,
	0xff, 0x4a, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0x00, 0x7c, 0x95, 0xcb, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserIntClient is the client API for UserInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserIntClient interface {
	// 权限校验
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	// 批量获取用户信息
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	// 批量获取用户信息
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error)
}

type userIntClient struct {
	cc *grpc.ClientConn
}

func NewUserIntClient(cc *grpc.ClientConn) UserIntClient {
	return &userIntClient{cc}
}

func (c *userIntClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/pb.UserInt/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userIntClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, "/pb.UserInt/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userIntClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersResp, error) {
	out := new(GetUsersResp)
	err := c.cc.Invoke(ctx, "/pb.UserInt/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIntServer is the server API for UserInt service.
type UserIntServer interface {
	// 权限校验
	Auth(context.Context, *AuthReq) (*AuthResp, error)
	// 批量获取用户信息
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
	// 批量获取用户信息
	GetUsers(context.Context, *GetUsersReq) (*GetUsersResp, error)
}

// UnimplementedUserIntServer can be embedded to have forward compatible implementations.
type UnimplementedUserIntServer struct {
}

func (*UnimplementedUserIntServer) Auth(ctx context.Context, req *AuthReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUserIntServer) GetUser(ctx context.Context, req *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserIntServer) GetUsers(ctx context.Context, req *GetUsersReq) (*GetUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}

func RegisterUserIntServer(s *grpc.Server, srv UserIntServer) {
	s.RegisterService(&_UserInt_serviceDesc, srv)
}

func _UserInt_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserInt/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserInt/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInt_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserInt/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserInt",
	HandlerType: (*UserIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _UserInt_Auth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserInt_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserInt_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.int.proto",
}
