# 为pod中的服务赋予发现服务和读取配置的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-role
  namespace: {{ $.Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - services
      - services/status
      - endpoints
      - endpoints/status
      - configmaps
      - configmaps/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
      - endpointslices/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-namespaces-binding
  namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
